---
- hosts: "{{ deploy_hosts|default('pgen-servers') }}"
  remote_user: root
  vars:
    app_path: ~/AdelaCourseManager  
  tasks:
    - name: create app directory
      file: path="{{ app_path }}" state=directory
    - name: upload war
      copy: src="{{ lookup('pipe', 'ls -1 build/libs/*.war') }}" dest="{{ app_path }}/AdelaCourseManager.war"
    - name: upload run script
      template: src=deploy/run dest="{{ app_path }}/run" mode=774
    - name: restart application
      shell: "{{ app_path }}/run restart chdir={{ app_path }}"
