---
- hosts: "{{ deploy_hosts|default('pgen-servers') }}"
  remote_user: root
  vars:
    app_path: ~/AdelaCourseManager  
  tasks:
    - name: stop application
      shell: "{{ app_path }}/run stop chdir={{ app_path }}"
    - name: remove the application
      file: path="{{ app_path }}" state=absent 
