endpoints:
   restart:
      enabled: true
   shutdown:
      enabled: true
   health:
      sensitive: false
spring: 
   datasource:
      driverClassName: org.h2.Driver
   jpa:
      show-sql: true

---
spring:
   profiles: postgres
   datasource:
      url: jdbc:postgresql:AdelaCourseManagerDB