#!/bin/bash

start() {
    echo "Starting AdelaCourseManager..."
    mkdir -p logs
    /usr/java/latest/bin/java -jar /home/jboss/adelaCourseManager-2015.99.0.0-SNAPSHOT.war &
    sleep 3
}

stop() {
    echo "Stopping AdelaCourseManager..."
    kill `ps -ef | awk '/[ad]delaCourseManager/{ print $2 }'`
    sleep 5
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
